/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiParseFlyerRouteImport } from './routes/api/parse-flyer'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseFlyerRoute = ApiParseFlyerRouteImport.update({
  id: '/api/parse-flyer',
  path: '/api/parse-flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/parse-flyer': typeof ApiParseFlyerRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/parse-flyer': typeof ApiParseFlyerRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/parse-flyer': typeof ApiParseFlyerRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/parse-flyer' | '/api/public/calendar/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/parse-flyer' | '/api/public/calendar/$token'
  id: '__root__' | '/' | '/api/parse-flyer' | '/api/public/calendar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiParseFlyerRoute: typeof ApiParseFlyerRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-flyer': {
      id: '/api/parse-flyer'
      path: '/api/parse-flyer'
      fullPath: '/api/parse-flyer'
      preLoaderRoute: typeof ApiParseFlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiParseFlyerRoute: ApiParseFlyerRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
